
image:
  file: .gitpod.Dockerfile

tasks:
  - name: initial
    init:
      sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd